### ISSUE TITLE
User statistics show each second day as zero

### ISSUE THREAD

**Issue by thirdinsight** [thundernest/addons-server#202]
### Describe the problem and steps to reproduce it:
Since two weeks the addon statistics show each second day as 0 (zero) resulting in a zigzag graph.
See https://addons.thunderbird.net/de/thunderbird/addon/auto-mark-folder-read/statistics/?last=30
.

### What did you expect to happen?
1. Don't show a zigzag graph but a normal graph.
2. Show the amount of daily users (the number) correctly.

### Anything else we should know?
Important: Please correct the amount of daily users (the number), since the statistics can't be acurate if each second day is reported as zero. Please correct the number for the past two weeks.

**Comment by thirdinsight** [comment]
Yes the wrong screenshot, sorry.
But a screenshot is not necessary, the text describes the problem.

**Comment by Sancus** [comment]
Should be resolved now but i'll keep an eye on it.

**Comment by thirdinsight** [comment]
Thanks!

**Comment by MyAddonsDev** [comment]
Unfortunately the problem is back again: Zero users since last Friday! :-(
